version: '3.4'

services:
  room_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  nosqldb:
    container_name: room_service_nosqldb
    restart: always
    ports:
      - "27017:27017"
  #cosmosdb:
  #  environment:
  #     - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
  #     - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
  #     - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
  #  ports:
  #     - 8081:8081
  #     - 10251-10254:10251-10254