version: '3.4'

services:
  room_service:
    image: ${DOCKER_REGISTRY-}roomservice
    build:
      context: .
      dockerfile: Dockerfile

  nosqldb:
    image: mongo

  #cosmosdb:
  #  image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
